---
- hosts: default
  sudo: yes
  vars_files:
    - my-vars.yml
  
  roles:
    - { role: OULibraries.centos7, tags: ["centos7"] }
    - { role: OULibraries.postfix-mta, tags: ["postfix"] }
    - { role: OULibraries.gitlab, tags: ["gitlab"] }
    - { role: OULibraries.users, tags: ["users"] }
